// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shop.Web.Models;

namespace Shop.Web.Migrations
{
    [DbContext(typeof(ShopDbContext))]
    [Migration("20190902212724_Update_Shop_List")]
    partial class Update_Shop_List
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Shop.Web.Models.ShopModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<double>("Distance");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(150);

                    b.Property<string>("MetricUnit")
                        .HasMaxLength(10);

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.Property<DateTime>("Timestamp");

                    b.HasKey("Id");

                    b.ToTable("Shops");

                    b.HasData(
                        new { Id = 1, Description = "Deals & Promotions", Distance = 180.0, ImageUrl = "https://cdn0.tnwcdn.com/wp-content/blogs.dir/1/files/2018/01/Amazon-Go-796x419.jpg", MetricUnit = "Km", Name = "Amazon Store", Timestamp = new DateTime(2019, 9, 3, 0, 27, 23, 617, DateTimeKind.Local) },
                        new { Id = 2, Description = "Clothes & Apparel.", Distance = 957.0, ImageUrl = "https://cdn.cnn.com/cnnnext/dam/assets/180517180219-jcpenney-store-front-exlarge-169.jpg", MetricUnit = "Km", Name = "JC Penny's", Timestamp = new DateTime(2019, 9, 3, 0, 27, 23, 636, DateTimeKind.Local) },
                        new { Id = 3, Description = "Chinese Multinational", Distance = 203.0, ImageUrl = "https://amp.businessinsider.com/images/5d361e6b100a242406627ce5-750-562.jpg", MetricUnit = "Km", Name = "Alibaba", Timestamp = new DateTime(2019, 9, 3, 0, 27, 23, 636, DateTimeKind.Local) },
                        new { Id = 4, Description = "Domestic retail store", Distance = 715.0, ImageUrl = "http://giftcardsgiveaway.net/wp-content/uploads/2016/01/bed-bath-and-beyond-img2.jpg", MetricUnit = "Km", Name = "BedBath & Beyond", Timestamp = new DateTime(2019, 9, 3, 0, 27, 23, 636, DateTimeKind.Local) },
                        new { Id = 5, Description = "Kenyan Supermarket", Distance = 386.0, ImageUrl = "https://businesstoday.co.ke/wp-content/uploads/2018/02/nakumatt-supermarket.jpg", MetricUnit = "Km", Name = "Nakumatt", Timestamp = new DateTime(2019, 9, 3, 0, 27, 23, 636, DateTimeKind.Local) },
                        new { Id = 6, Description = "Electrical appliances", Distance = 94.0, ImageUrl = "https://t1.hespress.com/files/aswakassalam_789587962.jpg", MetricUnit = "Km", Name = "Aswak Assalam", Timestamp = new DateTime(2019, 9, 3, 0, 27, 23, 636, DateTimeKind.Local) },
                        new { Id = 7, Description = "BIG on life", Distance = 873.0, ImageUrl = "http://www.fkservis.cz/uploads/references/66/oczm1481v8.jpg", MetricUnit = "Km", Name = "Makro", Timestamp = new DateTime(2019, 9, 3, 0, 27, 23, 636, DateTimeKind.Local) },
                        new { Id = 8, Description = "Chain store in SouthAfrica", Distance = 209.0, ImageUrl = "https://www.moneyweb.co.za/wp-content/uploads/2014/07/Pick-n-pay-3-2-Large1-500x333.jpg", MetricUnit = "Km", Name = "Pick n Pay", Timestamp = new DateTime(2019, 9, 3, 0, 27, 23, 636, DateTimeKind.Local) },
                        new { Id = 9, Description = "Large retail store", Distance = 534.0, ImageUrl = "https://media.bizj.us/view/img/425831/target*750xx600-338-0-19.jpg", MetricUnit = "Km", Name = "Target", Timestamp = new DateTime(2019, 9, 3, 0, 27, 23, 636, DateTimeKind.Local) },
                        new { Id = 10, Description = "Chain of hypermarkets", Distance = 357.0, ImageUrl = "https://n4f9d4s8.stackpathcdn.com/wp-content/uploads/2019/08/Walmart.jpg", MetricUnit = "Km", Name = "Walmart", Timestamp = new DateTime(2019, 9, 3, 0, 27, 23, 636, DateTimeKind.Local) }
                    );
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
